// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsudZ_A1UjvQ8fRieqDawrvlxSRV7LMlA',
    appId: '1:492470889587:web:f695c1bfa4c7df0920ce06',
    messagingSenderId: '492470889587',
    projectId: 'tennis-app-e2878',
    authDomain: 'tennis-app-e2878.firebaseapp.com',
    storageBucket: 'tennis-app-e2878.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH2Y8Qdfn3t5dXJNSXuu15N0FGb73gBXw',
    appId: '1:492470889587:android:7d0456c3bd8682b120ce06',
    messagingSenderId: '492470889587',
    projectId: 'tennis-app-e2878',
    storageBucket: 'tennis-app-e2878.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvFmJ9hHQYr4Y7GJetPhga1ZmL2Ak8HzM',
    appId: '1:492470889587:ios:f136678b07d3321420ce06',
    messagingSenderId: '492470889587',
    projectId: 'tennis-app-e2878',
    storageBucket: 'tennis-app-e2878.appspot.com',
    iosBundleId: 'com.example.tennisPlayerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvFmJ9hHQYr4Y7GJetPhga1ZmL2Ak8HzM',
    appId: '1:492470889587:ios:f136678b07d3321420ce06',
    messagingSenderId: '492470889587',
    projectId: 'tennis-app-e2878',
    storageBucket: 'tennis-app-e2878.appspot.com',
    iosBundleId: 'com.example.tennisPlayerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsudZ_A1UjvQ8fRieqDawrvlxSRV7LMlA',
    appId: '1:492470889587:web:85c00658e45417a620ce06',
    messagingSenderId: '492470889587',
    projectId: 'tennis-app-e2878',
    authDomain: 'tennis-app-e2878.firebaseapp.com',
    storageBucket: 'tennis-app-e2878.appspot.com',
  );
}
